_target_: "datamodule.OpenEarthMapDataModule"

# Dataset parameters
data_dir: "data/OpenEarthMap_wo_xBD/"
patch_size: 256
number_of_samples: 1000

classes:
  - "Road"

regions:
  train:
    - "al_qurnah"

  val:
    - "al_qurnah"

  test:
    - "koeln"

# DataLoader parameters
batch_size: 1
num_workers: 4
persistent_workers: true
pin_memory: true
