_target_: "datamodule.OpenEarthMapDataModule"

# Dataset parameters
data_dir: "data/OpenEarthMap_wo_xBD/"
patch_size: 256
number_of_samples: 1000

classes:
  - "Road"
  - "Building"

regions:
  train:
    - "chicago"

  val:
    - "chicago"

  test:
    - "chicago"

# DataLoader parameters
batch_size: 1
num_workers: 1
persistent_workers: false
pin_memory: false
