defaults:
  - model: vit
  - datamodule: default

hydra:
  run:
    dir: ./logs/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

logger:
  project: "ics3"
  save_dir: "./logs/"

experiment:
  name: "debug-model"
  tags: ["debug"]
  train: true
  test: true
  checkpoint: null # "./logs/ics3/lg60uve6/checkpoints/epoch=0-step=250.ckpt"

datamodule:
  batch_size: 4

loss:
  _target_: loss.BCEDiceLoss
  alpha: 1.0

optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-3

trainer:
  _target_: lightning.Trainer
  default_root_dir: "./logs/"
  log_every_n_steps: 1
  accelerator: "gpu"
  precision: 32
  max_epochs: 3
