defaults:
  - model: ics3
  - datamodule: default

hydra:
  run:
    dir: ./logs/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

logger:
  project: "ics3"
  save_dir: "./logs/"

experiment:
  name: "ics3-model"
  tags: ["ics3"]
  train: true
  test: true
  checkpoint: null

datamodule:
  batch_size: 4
  number_of_context_samples:
    train: 4
    val: 4
    test: 4

loss:
  _target_: loss.BCEDiceLoss
  alpha: 0.95

optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4
  weight_decay: 1e-3

lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: ${optimizer.lr}
  epochs: ${trainer.max_epochs}
  anneal_strategy: "cos"
  pct_start: 0.1
  div_factor: 25
  final_div_factor: 1e4

trainer:
  _target_: lightning.Trainer
  default_root_dir: "./logs/"
  log_every_n_steps: 1
  accelerator: "cuda"
  precision: "bf16-mixed"
  accumulate_grad_batches: 4
  max_epochs: 100
