defaults:
  - model: unet
  - datamodule: default

hydra:
  run:
    dir: ./logs/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

logger:
  project: "ics3"
  save_dir: "./logs/"

experiment:
  name: "unet-model"
  tags: ["unet"]
  train: true
  test: true
  checkpoint: null

datamodule:
  batch_size: 16

loss:
  _target_: loss.BCEDiceLoss
  alpha: 1.0

optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4
  weight_decay: 0.01

lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: ${optimizer.lr}
  epochs: ${trainer.max_epochs}
  steps_per_epoch: 197
  anneal_strategy: "cos"
  pct_start: 0.1
  div_factor: 25
  final_div_factor: 1e4

trainer:
  _target_: lightning.Trainer
  default_root_dir: "./logs/"
  log_every_n_steps: 1
  gradient_clip_val: 1
  accumulate_grad_batches: 2
  accelerator: "cuda"
  precision: 16
  max_epochs: 200
  check_val_every_n_epoch: 10
