defaults:
  - model: unet
  - datamodule: default

hydra:
  run:
    dir: ./logs/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

logger:
  project: "ics3"
  save_dir: "./logs/"

experiment:
  name: "unet-model"
  tags: ["unet"]
  train: true
  test: true
  checkpoint: null

datamodule:
  batch_size: 16

loss:
  _target_: loss.BCEDiceLoss
  alpha: 0.95

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-3
  weight_decay: 0.01

lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: ${optimizer.lr}
  epochs: ${trainer.max_epochs}
  steps_per_epoch: 394
  anneal_strategy: "cos"

trainer:
  _target_: lightning.Trainer
  default_root_dir: "./logs/"
  log_every_n_steps: 1
  accelerator: "cuda"
  precision: "bf16-mixed"
  max_epochs: 20
