defaults:
  - model: vit
  - datamodule: default

hydra:
  run:
    dir: ./logs/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

logger:
  project: "ics3"
  save_dir: "./logs/"

experiment:
  name: "vit-model"
  tags: ["vit"]
  train: true
  test: true
  checkpoint: null

datamodule:
  batch_size: 32

loss:
  _target_: loss.BCEDiceLoss
  alpha: 0.5

optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4
  weight_decay: 0.01

trainer:
  _target_: lightning.Trainer
  default_root_dir: "./logs/"
  log_every_n_steps: 1
  accelerator: "cuda"
  precision: "bf16-mixed"
  max_epochs: 20
