_target_: models.ics3.ICS3
sample_size: 224
patch_size: 16
hidden_dim: 768
in_channels: 3
out_channels: 1
layers_per_block: 2
block_out_channels:
  - 64
  - 128
  - 256
  - 512
down_block_types:
  - "DownBlock2D"
  - "DownBlock2D"
  - "DownBlock2D"
  - "AttnDownBlock2D"
up_block_types:
  - "AttnUpBlock2D"
  - "UpBlock2D"
  - "UpBlock2D"
  - "UpBlock2D"
